fix: remove settings from foundation/__init__.py to avoid automatic .env loading in container environments
Co-authored-by: chen-hui-zhe-xi<chenhui280@h-partners.com>



# message auto-generated for no-merge-commit merge:
!89 merge foundation-no-auto-env into develop

fix: remove settings from foundation/__init__.py to avoid automatic .env loading in container environments

Created-by: chen-hui-zhe-xi
Commit-by: chen-hui-zhe-xi
Merged-by: ZYQ5333
Description: <!--  Thanks for sending a pull request!  Here are some tips for you:

1) If this is your first time, please read our contributor guidelines: https://gitcode.com/openJiuwen/community/blob/master/CONTRIBUTING.md

2) If you want to contribute your code but don't know who will review and merge, please add label `openjiuwen-assistant` to the pull request, we will find and do it as soon as possible.
-->

**What type of PR is this?**
<!-- 
选择下面一种标签替换下方 `/kind <label>`，可选标签类型有：
- /kind bug 
- /kind task
- /kind feature
- /kind refactor
- /kind clean_code
如PR描述不符合规范，修改PR描述后需要/check-pr重新检查PR规范。
-->
/kind bug


**Self-checklist**:（**请自检，在[ ]内打上x，我们将检视你的完成情况，否则会导致pr无法合入**）

+ - [x] **设计**：PR对应的方案是否已经经过Maintainer评审，方案检视意见是否均已答复并完成方案修改
+ - [x] **测试**：PR中的代码是否已有UT/ST测试用例进行充分的覆盖，新增测试用例是否随本PR一并上库或已经上库
+ - [x] **验证**：PR描述信息中是否已包含对该PR对应的Feature、Refactor、Bugfix的预期目标达成情况的详细验证结果描述
+ - [x] **接口**：是否涉及对外接口变更，相应变更已得到接口评审组织的通过，API对应的注释信息已经刷新正确
+ - [x] **文档**：是否涉及官网文档修改，如果涉及请及时提交资料到Doc仓

<!-- **Special notes for your reviewers**: -->
<!-- + - [ ] 是否导致无法前向兼容 -->
<!-- + - [ ] 是否涉及依赖的三方库变更 -->


**这个PR的主要工作**
容器部署模式下，loweragent容器启动的时候，报这个错误：
```
ser ImageParser for .jfif
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/site-packages/openjiuwen_runtime/examples/lowcode_agent/__main__.py", line 22, in <module>
    main()
  File "/app/site-packages/openjiuwen_runtime/examples/lowcode_agent/__main__.py", line 17, in main
    from .lowcode_agent_runner import app
  File "/app/site-packages/openjiuwen_runtime/examples/lowcode_agent/lowcode_agent_runner.py", line 102, in <module>
    from openjiuwen_runtime.service.app.agent_app import AgentApp
  File "/app/site-packages/openjiuwen_runtime/service/__init__.py", line 56, in <module>
    from .app import BaseApp, AgentApp, PluginApp, AppGroup
  File "/app/site-packages/openjiuwen_runtime/service/app/__init__.py", line 10, in <module>
    from .base_app import BaseApp
  File "/app/site-packages/openjiuwen_runtime/service/app/base_app.py", line 21, in <module>
    from openjiuwen_runtime.foundation.log import get_logger
  File "/app/site-packages/openjiuwen_runtime/foundation/__init__.py", line 21, in <module>
    from .config import settings
  File "/app/site-packages/openjiuwen_runtime/foundation/config.py", line 119, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/app/site-packages/pydantic_settings/main.py", line 152, in __init__
    super().__init__(
  File "/app/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Settings
DB_TYPE
  Input should be 'mysql' or 'sqlite' [type=literal_error, input_value='none', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/literal_error
IP
  Field required [type=missing, input_value={'DB_TYPE': 'none'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
LOWCODE_IMAGE
  Field required [type=missing, input_value={'DB_TYPE': 'none'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing

```

这是因为foundation/__init__.py 有 settings 导入，所以，只要这个模块被导入，server/.env就一定需要的。 lowcode_agent_runner因为导入了foundation， 自动触发配置加载server/.env，进程部署的时候，loweragent因为运行在宿主机上，这个目录存在，所以不报错。但是容器部署，都没有server目录，也没有这个配置文件.env, 所以报错了。

See merge request: openJiuwen/agent-runtime!89